# Generated by Django 5.0.6 on 2024-11-14 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('user_fname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_fname', to=settings.AUTH_USER_MODEL)),
                ('user_lname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_lname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
