# Generated by Django 5.0.6 on 2024-11-14 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_images', verbose_name='Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_fname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_fname', to=settings.AUTH_USER_MODEL, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_lname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_lname', to=settings.AUTH_USER_MODEL, verbose_name='Último Nome'),
        ),
    ]
