# Generated by Django 5.0.6 on 2024-11-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user_avatar_alter_profile_user_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_avatar',
            new_name='avatar',
        ),
    ]
