# Generated by Django 5.1.2 on 2024-10-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poderoso_apps', '0005_exercicio_tempo_estimado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='tempo_estimado',
        ),
        migrations.AddField(
            model_name='planotreino',
            name='tempo_estimado',
            field=models.PositiveIntegerField(default=90, help_text='Tempo em minutos'),
            preserve_default=False,
        ),
    ]
